name: Upload Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - day-44

jobs:
  create-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create test report
        run: |
          echo "Day 44 CI Test Report" > test-report.txt
          echo "Test Status: PASS" >> test-report.txt
          echo "Artifact created successfully." >> test-report.txt

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.txt