name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      python_version: "3.12"
      run_tests: true

  docker:
    name: Build and Push Docker Image
    needs: build-test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: komalmankari26/github-actions-capstone
      tag: latest
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    name: Production Deployment
    needs: docker
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy application
        run: |
          echo "Deploying image: ${{ needs.docker.outputs.image_url }}"
          echo "Deployment completed successfully."