name: Secrets Test Workflow
on:
  workflow_dispatch:

jobs:
  secrets-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret is set
        env:
            MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
            if [ -z "$MY_SECRET" ]; then
              echo "Secret is not set."
            else
              echo "Secret is set."
            fi   