name: Secrets Test

on:
  push:
    branches:
      - day-44
  workflow_dispatch:

jobs:
  secret-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret is set
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          if [ -n "$MY_SECRET" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi